controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


product/show_all:
    path: /product/show_all
    controller: App\Controller\ProductController::showAll
